language: ruby
rvm:
  - 2.1.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
sudo: false
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - bundle exec rake test_app
script:
  - bundle exec rspec spec
